-- Local-first L1: server-side ciphertext-only op-log.
-- One row per encrypted op frame. The server stores the opaque frame bytes and
-- never decrypts them. Only the plaintext header (device_id, op_id, seq) is
-- read, to fill the index columns. Feature is OFF unless FINLYNQ_LOCAL_FIRST_API=1.
--
-- id is the pull cursor (monotonic per table). UNIQUE(user_id, op_id) makes
-- append idempotent (ON CONFLICT DO NOTHING).
-- No data_version trigger: nothing here is read by ETag routes.
-- Wipe/delete: explicit delete in deleteAllUserDataTx (an FK to users is not coverage).

CREATE TABLE IF NOT EXISTS lf_op_frame (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id text NOT NULL,
  op_id text NOT NULL,
  seq integer NOT NULL,
  frame bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lf_op_frame_user_op_uniq UNIQUE (user_id, op_id)
);
CREATE INDEX IF NOT EXISTS lf_op_frame_user_id_idx ON lf_op_frame (user_id, id);
