// @vitest-environment node
// W6-01: generated by the W6 planner. Do not edit by hand.
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";

const css = readFileSync("src/app/globals.css", "utf8");
const block = (sel: RegExp) => {
  const m = css.match(sel);
  if (!m) throw new Error(`block not found: ${sel}`);
  return m[1];
};

describe("W6-01 status tokens", () => {
  it("@theme maps pos, warning and info to their own variables", () => {
    const theme = block(/@theme inline \{([\s\S]*?)\n\}/);
    expect(theme).toContain("--color-pos: var(--pos);");
    expect(theme).toContain("--color-warning: var(--warning);");
    expect(theme).toContain("--color-info: var(--info);");
    expect(theme).toContain("--color-neg: var(--destructive);");
  });

  it("light :root defines AA-contrast pos/warning/info values", () => {
    const root = block(/\n:root \{([\s\S]*?)\n\}/);
    expect(root).toContain("--pos: oklch(0.55 0.11 170);");
    expect(root).toContain("--warning: oklch(0.56 0.14 60);");
    expect(root).toContain("--info: oklch(0.52 0.13 250);");
  });

  it(".dark defines pos/warning/info values", () => {
    const dark = block(/\n\.dark \{([\s\S]*?)\n\}/);
    expect(dark).toContain("--pos: oklch(0.75 0.11 170);");
    expect(dark).toContain("--warning: oklch(0.80 0.15 75);");
    expect(dark).toContain("--info: oklch(0.74 0.11 245);");
  });

  it("chart-2 stays the chart teal (charts unchanged)", () => {
    expect(css).toContain("--color-chart-2: var(--chart-2);");
    expect(css).toContain("--chart-2: oklch(0.72 0.13 170);");
    expect(css).toContain("--chart-2: oklch(0.75 0.11 170);");
  });
});
