/**
 * @vitest-environment jsdom
 */
// W6-04: generated by the W6 planner. Do not edit by hand.
import { describe, it, expect, vi, afterEach } from "vitest";
import * as React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/link", () => ({
  default: ({ children, href, ...p }: React.PropsWithChildren<{ href: string }>) => React.createElement("a", { href, ...p }, children),
}));
vi.mock("next/navigation", () => ({
  useSearchParams: () => new URLSearchParams(), useRouter: () => ({ push: vi.fn(), back: vi.fn() }), usePathname: () => "/whats-new" }));

import WhatsNewPage from "@/app/(app)/whats-new/page";
import InfoPage from "@/app/(app)/account/info/page";

type Reply = { ok: boolean; status: number; body: unknown };
function stubFetch(handler: (url: string) => Reply) {
  const fn = vi.fn(async (url: string) => {
    const r = handler(String(url));
    return { ok: r.ok, status: r.status, json: async () => r.body };
  });
  vi.stubGlobal("fetch", fn);
  return fn;
}

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("W6-04 whats-new error state", () => {
  it("shows ErrorState when announcements fail and recovers on retry", async () => {
    let calls = 0;
    stubFetch((url) => {
      if (url === "/api/announcements") {
        calls++;
        return calls === 1 ? { ok: false, status: 500, body: null } : { ok: true, status: 200, body: [] };
      }
      return { ok: true, status: 200, body: null };
    });
    render(<WhatsNewPage />);
    const alert = await screen.findByRole("alert");
    expect(alert.textContent).toContain("Couldn't load announcements");
    fireEvent.click(screen.getByText("Try again"));
    await waitFor(() => expect(screen.queryByRole("alert")).toBeNull());
    expect(await screen.findByText(/No announcements yet/)).toBeTruthy();
    expect(calls).toBe(2);
  });
});

describe("W6-04 account info loading and error states", () => {
  it("shows the shimmer skeleton instead of plain loading text", () => {
    vi.stubGlobal("fetch", vi.fn(() => new Promise(() => {})));
    const { container } = render(<InfoPage />);
    expect(container.querySelectorAll(".animate-shimmer").length).toBeGreaterThan(0);
    expect(screen.queryByText("Loading profile...")).toBeNull();
  });

  it("shows ErrorState when the profile fails and refetches on retry", async () => {
    let calls = 0;
    stubFetch((url) => {
      if (url === "/api/user/me") {
        calls++;
        return calls === 1
          ? { ok: false, status: 500, body: null }
          : { ok: true, status: 200, body: { username: "u1", email: "u1@example.com", displayName: "U One", phone: null, avatarUrl: null } };
      }
      return { ok: true, status: 200, body: null };
    });
    render(<InfoPage />);
    const alert = await screen.findByRole("alert");
    expect(alert.textContent).toContain("Couldn't load your profile");
    fireEvent.click(screen.getByText("Try again"));
    await waitFor(() => expect(screen.queryByRole("alert")).toBeNull());
    expect(calls).toBe(2);
  });
});
