// @vitest-environment node
// W6-22: generated by the W6 planner. Do not edit by hand.
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";

const PALETTE = /\b(bg|text|border|ring|from|to|via|fill|stroke|outline|divide|ring-offset|shadow|decoration|accent|caret|placeholder|border-[trblxy]|border-[se])-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-[0-9]{2,3}\b/g;
const FILES: string[] = [
  "src/app/(app)/portfolio/_components/allocation-charts.tsx",
  "src/app/(app)/portfolio/_components/benchmark-chart.tsx",
  "src/app/(app)/portfolio/_components/etf-xray-card.tsx",
  "src/app/(app)/portfolio/_components/holdings-by-account.tsx",
  "src/app/(app)/portfolio/_components/holdings-table.tsx",
];
const ARIA: [string, string, number][] = [
  ["src/app/(app)/portfolio/_components/etf-xray-card.tsx", "aria-label=\"Previous page\"", 1],
  ["src/app/(app)/portfolio/_components/etf-xray-card.tsx", "aria-label=\"Next page\"", 1],
];
const SKELETON: [string, string, number][] = [
];

describe("W6-22 design-system sweep", () => {
  for (const f of FILES) {
    it(`${f} has no hardcoded palette colour classes`, () => {
      expect(readFileSync(f, "utf8").match(PALETTE) ?? []).toEqual([]);
    });
  }
  for (const [f, attr, n] of ARIA) {
    it(`${f} names its icon-only button: ${attr}`, () => {
      expect(readFileSync(f, "utf8").split(attr).length - 1).toBe(n);
    });
  }
  for (const [f, old] of SKELETON) {
    it(`${f} skeletons use animate-shimmer, not ${old}`, () => {
      const src = readFileSync(f, "utf8");
      expect(src.includes(old)).toBe(false);
      expect(src.includes("animate-shimmer")).toBe(true);
    });
  }
});
