// @vitest-environment node
// W6-21: generated by the W6 planner. Do not edit by hand.
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";

const PALETTE = /\b(bg|text|border|ring|from|to|via|fill|stroke|outline|divide|ring-offset|shadow|decoration|accent|caret|placeholder|border-[trblxy]|border-[se])-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-[0-9]{2,3}\b/g;
const FILES: string[] = [
  "src/app/(app)/import/pending/_components/bank-pane.tsx",
  "src/app/(app)/import/pending/_components/reconcile-header.tsx",
  "src/app/(app)/import/pending/_components/staged-list-view.tsx",
  "src/app/(app)/import/pending/_components/staged-pane.tsx",
];
const ARIA: [string, string, number][] = [
  ["src/app/(app)/import/pending/_components/bank-pane.tsx", "aria-label=\"Remove 'missing from statement' flag\"", 1],
  ["src/app/(app)/import/pending/_components/bank-pane.tsx", "aria-label=\"Mark as missing from this statement\"", 1],
  ["src/app/(app)/import/pending/_components/staged-pane.tsx", "aria-label=\"Unlink\"", 1],
  ["src/app/(app)/import/pending/_components/staged-pane.tsx", "aria-label=\"Un-skip\"", 1],
  ["src/app/(app)/import/pending/_components/staged-pane.tsx", "aria-label=\"Link to a DB row\"", 1],
  ["src/app/(app)/import/pending/_components/staged-pane.tsx", "aria-label=\"Mark as already imported\"", 1],
];
const SKELETON: [string, string, number][] = [
];

describe("W6-21 design-system sweep", () => {
  for (const f of FILES) {
    it(`${f} has no hardcoded palette colour classes`, () => {
      expect(readFileSync(f, "utf8").match(PALETTE) ?? []).toEqual([]);
    });
  }
  for (const [f, attr, n] of ARIA) {
    it(`${f} names its icon-only button: ${attr}`, () => {
      expect(readFileSync(f, "utf8").split(attr).length - 1).toBe(n);
    });
  }
  for (const [f, old] of SKELETON) {
    it(`${f} skeletons use animate-shimmer, not ${old}`, () => {
      const src = readFileSync(f, "utf8");
      expect(src.includes(old)).toBe(false);
      expect(src.includes("animate-shimmer")).toBe(true);
    });
  }
});
